steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/andrew-ku-links/links:latest', '.']
#- name: 'gcr.io/cloud-builders/gcloud'
#  args: ['app', 'deploy', '--image-url=gcr.io/andrew-ku-links/links:latest']
images: ['gcr.io/andrew-ku-links/links:latest']
