name: Docker Build and Push and Deploy

on:
  push:
    branches:
      - 'master'
      
env: 
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
      
jobs:
  docker:
    if: github.repository == 'Drookoo/links'
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/drookoo/links:latest
